### ISSUE TITLE
Can you provide a GBR file? I generated a GBR file using a PCB file, which cannot be read by the manufacturer

### ISSUE THREAD

**Issue by ws786873** [oskitone/poly555#3]
Can you provide a GBR file? I generated a GBR file using a PCB file, which cannot be read by the manufacturer

**Comment by rocktronica** [comment]
@ws786873 Walk me through your process and which manufacturer? I successfully make gerber files from the Kicad project in this repo. Maybe it's a software version or vendor input problem?

^ seems like the root cause problem, which I'd like to fix. Adding GBR files isn't a great fix if the underlying Kicad project still isn't working as expected.

To the prospect of adding GBR files explicitly, I'm reluctant because:

1. It adds friction to the commit process. Making new gerber files doesn't take long, but it's easy to forget, can't be easily automated, and has enough vendor nuance that it isn't straightforward, IMHO.
2. For the same reason the STLs aren't included but their OpenSCAD is, source code could should ideally be just that: _source, not compiled output_. 

Thanks for bringing it up tho. Good question. And thanks for your patience in my responding. :)

**Comment by ws786873** [comment]
> @ws786873 Walk me through your process and which manufacturer? I successfully make gerber files from the Kicad project in this repo. Maybe it's a software version or vendor input problem?
> 
> ^ seems like the root cause problem, which I'd like to fix. Adding GBR files isn't a great fix if the underlying Kicad project still isn't working as expected.
> 
> To the prospect of adding GBR files explicitly, I'm reluctant because:
> 
> 1. It adds friction to the commit process. Making new gerber files doesn't take long, but it's easy to forget, can't be easily automated, and has enough vendor nuance that it isn't straightforward, IMHO.
> 2. For the same reason the STLs aren't included but their OpenSCAD is, source code could should ideally be just that: _source, not compiled output_.
> 
> Thanks for bringing it up tho. Good question. And thanks for your patience in my responding. :)

I used kicd5 1.1 and kicad5. 99 (beta version of 6.0) generates GBR files. The manufacturer is a local military quality manufacturer. Their engineers said that the manufacturing software failed to read the files. I saw a screenshot of his software, which seems to be the same software as JLC.

**Comment by rocktronica** [comment]
Gotcha, thanks for the update.

Gerbers from 5.1.9-0-10_14 have worked fine for me at JLC (tho they didn't love my paneling 😅). Seems odd that a version between the two you tried could be good but the others bad.

Besides the actual gerber exports being invalid, another variable is the manufacturer. If you try your GBRs w/ JLC and they accept them, we can know it's a manufacturing input issue.

I suspect it's one of those two. Otherwise, I'll keep an eye on this issue when I update to Kicad 6 and will see how it goes

**Comment by ws786873** [comment]
JLC can accept them ,thank you.
